### PR TITLE
add some automagic to handling projects, milestones, and labels

### PR DESCRIPTION
**Pull request by shawncatz**
the `config.yml` file contains a list of repositories, milestones, and labels
the `main.go` program does the following:
* ensure that each listed milestone has a corresponding organization project (to collect all of the work for a milestone in a single view)
* ensure that each repo has the each of the labels and milestones

currently, it does not update existing labels and milestones, if they exist, it moves on.
it should be able to handle updating labels and milestones as well (so that we can change the due date of a milestone in the config and it will update across all repos)

This is still a work in progress

### CODE REVIEW

**Comment by notzippy** [comment]
This is a nice tool ! Any reason why you used your own fork of https://github.com/google/go-github ?
Do you have any samples of its output ?

**Comment by shawncatz** [comment]
right now, the output is just informational:
```
create project on org: v0.14
create project on org: v0.15
create project on org: v0.16
create milestone v0.16 on repo revel
create label type-bug on repo revel
create label type-bug-windows on repo revel
create label type-docs on repo revel
create label type-enhancement on repo revel
create label type-feature on repo revel
create label status-waiting-for-reply on repo cmd
create label type-bug-windows on repo cmd
create milestone Backlog on repo modules
create label status-analysis on repo modules
create label status-waiting-for-reply on repo modules
create label type-bug-windows on repo modules
create milestone Backlog on repo examples
create milestone v0.15 on repo examples
create milestone v0.16 on repo examples
create label status-analysis on repo examples
create label status-waiting-for-reply on repo examples
create label type-bug-windows on repo examples
create label type-enhancement on repo examples
```

I used my fork because I'm in the process of getting a PR merged to add support for organization projects on go-github (it wasn't there, so I added it :) )
https://github.com/google/go-github/pull/599

**Comment by shawncatz** [comment]
because there are more labels on the revel repo than fit in a single paged response, it wasn't seeing all of the labels... I added some additional functionality to handle that... the correct informational output is:
```
create project on org: v0.14
create project on org: v0.15
create project on org: v0.16
create milestone v0.16 on repo revel
create label status-waiting-for-reply on repo cmd
create label type-bug-windows on repo cmd
create milestone Backlog on repo modules
create label status-analysis on repo modules
create label status-waiting-for-reply on repo modules
create label type-bug-windows on repo modules
create milestone Backlog on repo examples
create milestone v0.15 on repo examples
create milestone v0.16 on repo examples
create label status-analysis on repo examples
create label status-waiting-for-reply on repo examples
create label type-bug-windows on repo examples
create label type-enhancement on repo examples
```

**Review by pedromorgan — APPROVED** [review]
Looks good to me..

**Comment by shawncatz** [comment]
still getting the travis stuff working...

**Comment by shawncatz** [comment]
having trouble getting this working with my fork... going to just wait until the PR with go-github is complete.

**Comment by pedromorgan** [comment]
Can I suggest to merge this straight into master for the time being.. please..

this will help with my go get for rf.com

**Comment by shawncatz** [comment]
It doesn't have anything to do with rf.com... these changes are specifically to manage milestones and labels... the code has been run manually, so the milestones and labels all exist on all of the repos (at least the ones referenced in `config.yml`)

**Comment by pedromorgan** [comment]
So what I want is to run that code in an rf.com @job.. so site updates itself automatically.. 

idea in my head stupid anyway ;-)

How would we add a hook from github.com into rf.com ?

**Comment by shawncatz** [comment]
You can probably set that up in a travis job

-- 
Shawn Catanzarite
408-605-7744
http://shawncatz.com/
http://linkedin.com/in/shawncatanzarite

**Comment by shawncatz** [comment]
apparently the problem I'm running into is that travis does not expose secrets to PRs from other repos... so I'm going to merge this to make sure it runs.

**Pull request merged**
